# Generated by Django 4.2.7 on 2023-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='envio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
